---
- name: import generic tasks
  import_tasks: common.yml

- name: include vars
  include_vars: vars/vars.yml

- name: install neutron
  apt:
    name: ["neutron-api", "neutron-rpc-server"]
    state: latest

- name: configure neutron
  ini_file:
    path: /etc/neutron/neutron.conf
    section: "{{item.section}}"
    option: "{{item.option}}"
    value: "{{item.value}}"
  with_items:
    - { section: "database", option: "connection", value: "mysql+pymysql://neutron:{{password}}@mysql/neutron" }
    - { section: "DEFAULT", option: "core_plugin", value: "ml2" }
    - { section: "DEFAULT", option: "service_plugins", value: "router,segments,port_forwarding" }
    - { section: "DEFAULT", option: "allow_overlapping_ips", value: "true" }
    - { section: "DEFAULT", option: "transport_url", value: "rabbit://openstack:{{password}}@rabbit" }
    - { section: "DEFAULT", option: "notify_nova_on_port_status_changes", value: "true" }
    - { section: "DEFAULT", option: "notify_nova_on_port_data_changes", value: "true" }
    - { section: "DEFAULT", option: "router_distributed", value: "true" }
    - { section: "DEFAULT", option: "l3_ha", value: "true" }
    - { section: "oslo_concurrency", option: "lock_path", value: "/var/lib/neutron/tmp" }
    - { section: "keystone_authtoken", option: "www_authenticate_uri", value: "http://keystone:5000" }
    - { section: "keystone_authtoken", option: "auth_url", value: "http://keystone:5000" }
    - { section: "keystone_authtoken", option: "memcached_servers", value: "keystone:11211" }
    - { section: "keystone_authtoken", option: "auth_type", value: "password" }
    - { section: "keystone_authtoken", option: "project_domain_name", value: "Default" }
    - { section: "keystone_authtoken", option: "user_domain_name", value: "Default" }
    - { section: "keystone_authtoken", option: "project_name", value: "service" }
    - { section: "keystone_authtoken", option: "username", value: "nova" }
    - { section: "keystone_authtoken", option: "password", value: "{{password}}" }
    - { section: "keystone_authtoken", option: "region_name", value: "RegionOne" }      # NOTE debian package is overwritting with regionOne (this is a bug IMO)
    - { section: "nova", option: "auth_url", value: "http://keystone:5000" }
    - { section: "nova", option: "auth_type", value: "password" }
    - { section: "nova", option: "project_domain_name", value: "Default" }
    - { section: "nova", option: "user_domain_name", value: "Default" }
    - { section: "nova", option: "region_name", value: "RegionOne" }
    - { section: "nova", option: "project_name", value: "service" }
    - { section: "nova", option: "username", value: "nova" }
    - { section: "nova", option: "password", value: "{{password}}" }
  notify:
    - restart neutron
- name: configure neutron ml2
  ini_file:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    section: "{{item.section}}"
    option: "{{item.option}}"
    value: "{{item.value}}"
  with_items:
    - { section: "ml2", option: "type_drivers", value: "flat,vlan,vxlan" }
    - { section: "ml2", option: "tenant_network_types", value: "vxlan" }
    - { section: "ml2", option: "mechanism_drivers", value: "openvswitch,l2population" }
    - { section: "ml2", option: "extension_drivers", value: "port_security" }
    - { section: "ml2_type_flat", option: "flat_networks", value: "provider" }
    - { section: "ml2_type_vxlan", option: "vni_ranges", value: "1:1000" }
    - { section: "securitygroup", option: "enable_ipset", value: "true" }
  notify:
    - restart neutron

- name: initiate neutron database
  shell: su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron && touch /root/.ansible_initiate_neutron_db
  args:
    creates: /root/.ansible_initiate_neutron_db
