---
- name: import generic tasks
  import_tasks: common.yml

- name: include vars
  include_vars: vars/vars.yml

- name: install neutron
  apt:
    name: ["neutron-server", "neutron-plugin-ml2", "neutron-openvswitch-agent", "neutron-l3-agent", "neutron-dhcp-agent", "neutron-metadata-agent"]
    state: latest

- name: create br-ex ovs bridge
  openvswitch_bridge:
    bridge: br-ex
    fail_mode: standalone
    state: present

- name: add ens5 in br-ex
  openvswitch_port:
    bridge: br-ex
    port: ens5
    state: present

- name: configure neutron
  ini_file:
    path: /etc/neutron/neutron.conf
    section: "{{item.section}}"
    option: "{{item.option}}"
    value: "{{item.value}}"
  with_items:
    - { section: "database", option: "connection", value: "mysql+pymysql://neutron:{{password}}@mysql/neutron" }
    - { section: "DEFAULT", option: "core_plugin", value: "ml2" }
    - { section: "DEFAULT", option: "service_plugins", value: "router,segments" }
    - { section: "DEFAULT", option: "allow_overlapping_ips", value: "true" }
    - { section: "DEFAULT", option: "transport_url", value: "rabbit://openstack:{{password}}@rabbit" }
    - { section: "DEFAULT", option: "notify_nova_on_port_status_changes", value: "true" }
    - { section: "DEFAULT", option: "notify_nova_on_port_data_changes", value: "true" }
    - { section: "DEFAULT", option: "router_distributed", value: "true" }
    - { section: "oslo_concurrency", option: "lock_path", value: "/var/lib/neutron/tmp" }
    - { section: "keystone_authtoken", option: "www_authenticate_uri", value: "http://keystone:5000" }
    - { section: "keystone_authtoken", option: "auth_url", value: "http://keystone:5000" }
    - { section: "keystone_authtoken", option: "memcached_servers", value: "keystone:11211" }
    - { section: "keystone_authtoken", option: "auth_type", value: "password" }
    - { section: "keystone_authtoken", option: "project_domain_name", value: "Default" }
    - { section: "keystone_authtoken", option: "user_domain_name", value: "Default" }
    - { section: "keystone_authtoken", option: "project_name", value: "service" }
    - { section: "keystone_authtoken", option: "username", value: "nova" }
    - { section: "keystone_authtoken", option: "password", value: "{{password}}" }
    - { section: "nova", option: "auth_url", value: "http://keystone:5000" }
    - { section: "nova", option: "auth_type", value: "password" }
    - { section: "nova", option: "project_domain_name", value: "Default" }
    - { section: "nova", option: "user_domain_name", value: "Default" }
    - { section: "nova", option: "region_name", value: "RegionOne" }
    - { section: "nova", option: "project_name", value: "service" }
    - { section: "nova", option: "username", value: "nova" }
    - { section: "nova", option: "password", value: "{{password}}" }
  notify:
    - restart neutron
- name: configure neutron ml2
  ini_file:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    section: "{{item.section}}"
    option: "{{item.option}}"
    value: "{{item.value}}"
  with_items:
    - { section: "ml2", option: "type_drivers", value: "flat,vlan,vxlan" }
    - { section: "ml2", option: "tenant_network_types", value: "vxlan" }
    - { section: "ml2", option: "mechanism_drivers", value: "openvswitch,l2population" }
    - { section: "ml2", option: "extension_drivers", value: "port_security" }
    - { section: "ml2_type_flat", option: "flat_networks", value: "provider" }
    - { section: "ml2_type_vxlan", option: "vni_ranges", value: "1:1000" }
    - { section: "securitygroup", option: "enable_ipset", value: "true" }
  notify:
    - restart neutron
- name: configure neutron l2 agent
  ini_file:
    path: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    section: "{{item.section}}"
    option: "{{item.option}}"
    value: "{{item.value}}"
  with_items:
    - { section: "agent", option: "tunnel_types", value: "vxlan" }
    - { section: "agent", option: "l2_population", value: "true" }
    - { section: "agent", option: "arp_responder", value: "true" }
    - { section: "agent", option: "enable_distributed_routing", value: "true" }
    - { section: "ovs", option: "local_ip", value: "{{ansible_host}}" }
    - { section: "ovs", option: "bridge_mappings", value: "provider:br-ex" }
    - { section: "securitygroup", option: "enable_security_group", value: "true" }
    - { section: "securitygroup", option: "firewall_driver", value: "openvswitch" }
  notify:
    - restart neutron
- name: configure neutron l3 agent
  ini_file:
    path: /etc/neutron/l3_agent.ini
    section: "{{item.section}}"
    option: "{{item.option}}"
    value: "{{item.value}}"
  with_items:
    - { section: "DEFAULT", option: "interface_driver", value: "openvswitch" }
    - { section: "DEFAULT", option: "agent_mode", value: "dvr_snat" }
  notify:
    - restart neutron
- name: configure neutron dhcp agent
  ini_file:
    path: /etc/neutron/dhcp_agent.ini
    section: "{{item.section}}"
    option: "{{item.option}}"
    value: "{{item.value}}"
  with_items:
    - { section: "DEFAULT", option: "interface_driver", value: "openvswitch" }
    - { section: "DEFAULT", option: "dhcp_driver", value: "neutron.agent.linux.dhcp.Dnsmasq" }
    - { section: "DEFAULT", option: "enable_isolated_metadata", value: "true" }
  notify:
    - restart neutron
- name: configure neutron metadata agent
  ini_file:
    path: /etc/neutron/metadata_agent.ini
    section: "{{item.section}}"
    option: "{{item.option}}"
    value: "{{item.value}}"
  with_items:
    - { section: "DEFAULT", option: "nova_metadata_host", value: "nova" }
    - { section: "DEFAULT", option: "metadata_proxy_shared_secret", value: "{{password}}" }
  notify:
    - restart neutron

- name: initiate neutron database
  shell: su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron && touch /root/.ansible_initiate_neutron_db
  args:
    creates: /root/.ansible_initiate_neutron_db
