- name: restart nova
  service:
    name: "{{item}}"
    state: restarted
  with_items:
    - "nova-api"
    - "nova-api-metadata"
    - "nova-serialproxy"
    - "nova-spicehtml5proxy"
    - "nova-scheduler"
    - "nova-conductor"
