---
- name: delete 127.0.1.1 line in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1.+'
    state: absent
- name: delete ipv6 lines in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: 'ip6'
    state: absent
- name: add hosts in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
    state: present
    regexp: '.*{{ hostvars[item].inventory_hostname }}$'
  with_items: "{{ groups.all }}"
- name: install common packages
  apt:
    name: ["lnav", "ccze", "tmux", "crudini"]
    state: latest
- name: install plik
  get_url:
    url: https://plik.arno.ovh/clients/linux-amd64/plik
    dest: /usr/local/bin/plik
    mode: '0755'
- name: configure plik
  copy:
    dest: "/root/.plikrc"
    content: |
      Url = "https://plik.arno.ovh"

