#!/bin/bash

# Setup logging stdout + stderr to logfile
log_file="/var/log/postinstall.log"

function log_handler {
  while IFS='' read -r output; do
    echo $output
    echo "$(date) - $output" >> $log_file
  done
}

exec &> >(log_handler)

# Update packages
apt update
apt -y install software-properties-common
add-apt-repository -y cloud-archive:pike
apt update
apt -y purge cloud-init
apt -y dist-upgrade
apt -y install python chrony lnav

# Deployer will use this key (I named it zob) to connect to other machines
# Note: this is not very secure to use this key because:
# - it is on github without any protection
# - it does not have any password
cat <<EOF >/root/.ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDY15cdBmIs2XOpe4EiFCsaY6bmUmK/GysMoLl4UG51JCfJwvwoWCoA+6mDIbymZxhxq9IGxilp/yTA6WQ9s/5pBag1cUMJmFuda9PjOkXl04jgqh5tR6I+GZ97AvCg93KAECis5ubSqw1xOCj4utfEUtPoF1OuzqM/lE5mY4N6VKXn+fT7pCD6cifBEs6JHhVNvs5OLLp/tO8Pa3kKYQOdyS0xc3rh+t2lrzvKUSWGZbX+dLiFiEpjsUL3tDqzkEMNUn4pdv69OJuzWHCxRWPfdrY9Wg0j3mJesP29EBht+w+EC9/kBKq+1VKdmsXUXAcjEvjovVL8l1BrX3BY0R8D zob
EOF

# Configure network
# ens3 --> Ext-Net interface. Mostly used to access API over regular internet connection
# ens4 --> management interface. Mostly used by some OpenStack services to communicate
# ens5 --> public interface. Used by neutron and compute to handle VM <--> Internet connectivity
cat <<'EOF' > /etc/network/interfaces
auto lo
iface lo inet loopback

auto ens3
iface ens3 inet dhcp

auto ens4
iface ens4 inet dhcp

auto ens5
iface ens5 inet manual
up ip link set dev $IFACE up
up ip link set dev $IFACE mtu 9000
down ip link set dev $IFACE down
EOF

# ens3 is already set up by ubuntu
ifup ens4
ifup ens5

echo 'done'
